[workspace]
resolver = "2"
members = [
    "server",
    "client",
    "shared",
]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
